# Generated by Django 3.2.15 on 2022-11-09 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enzyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reversible', models.BooleanField()),
                ('abbreviation', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('link', models.URLField()),
                ('public', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=10)),
                ('ball_and_stick_image', models.ImageField(upload_to='')),
                ('space_filling_image', models.ImageField(upload_to='')),
                ('link', models.URLField()),
                ('public', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('public', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PathwayMolecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pathway')),
                ('substrate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.molecule')),
            ],
        ),
        migrations.CreateModel(
            name='PathwayEnzyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('limiting', models.BooleanField()),
                ('enzyme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.enzyme')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pathway')),
            ],
        ),
        migrations.AddField(
            model_name='pathway',
            name='enzymes',
            field=models.ManyToManyField(related_name='pathways_enzyme', through='api.PathwayEnzyme', to='api.Enzyme'),
        ),
        migrations.AddField(
            model_name='pathway',
            name='molecules',
            field=models.ManyToManyField(related_name='pathways_molecule', through='api.PathwayMolecule', to='api.Molecule'),
        ),
        migrations.AddField(
            model_name='enzyme',
            name='cofactors',
            field=models.ManyToManyField(related_name='enzymes_cofactors', to='api.Molecule'),
        ),
        migrations.AddField(
            model_name='enzyme',
            name='products',
            field=models.ManyToManyField(related_name='enzymes_products', to='api.Molecule'),
        ),
        migrations.AddField(
            model_name='enzyme',
            name='substrates',
            field=models.ManyToManyField(related_name='enzymes_substrates', to='api.Molecule'),
        ),
    ]
