# Generated by Django 4.1.3 on 2022-11-08 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.CharField(default='', max_length=30)),
                ('link', models.URLField()),
                ('abbreviation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('link', models.URLField()),
                ('public', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enzyme',
            fields=[
                ('molecule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.molecule')),
                ('reversible', models.BooleanField()),
                ('cofactors', models.ManyToManyField(related_name='cofactor', to='api.molecule')),
                ('products', models.ManyToManyField(related_name='product', to='api.molecule')),
                ('substrates', models.ManyToManyField(related_name='substrate', to='api.molecule')),
            ],
            bases=('api.molecule',),
        ),
        migrations.CreateModel(
            name='PathwayMolecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pathway')),
                ('substrate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.molecule')),
            ],
        ),
        migrations.AddField(
            model_name='pathway',
            name='substrates',
            field=models.ManyToManyField(through='api.PathwayMolecule', to='api.molecule'),
        ),
        migrations.CreateModel(
            name='PathwayEnzyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pathway')),
                ('enzyme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.enzyme')),
            ],
        ),
        migrations.AddField(
            model_name='pathway',
            name='enzymes',
            field=models.ManyToManyField(related_name='enzyme', through='api.PathwayEnzyme', to='api.enzyme'),
        ),
    ]
