# Generated by Django 3.2.15 on 2022-11-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enzyme',
            name='reversible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pathwayenzyme',
            name='limiting',
            field=models.BooleanField(default=False),
        ),
    ]
