# Docker compose file for running production Django server and database in containers

version: "3.2"
services:
  db:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    volumes: # you must set the environment variable BIOPATH_ROOT_PATH on your machine
             #  for me this was just
             #   'export BIOPATH_ROOT_PATH="~/Users/joshuaschmitz/Projects/BioPath"'
      - "${BIOPATH_ROOT_PATH}/postgres:/var/lib/postgresql/data/"
    environment:
      # these are the same as those in backend container; look at .env.dev
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=BioPath
    ports:
      - '5432:5432'

  backend:
    container_name: backend
    platform: linux/amd64
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: backend
    ports:
      - "80:80"
      - "8000:8000"
    env_file: backend/.env.dev

  # AWS specific configuration details
  # logging:
  #   driver: awslogs 
  #   options:
  #     awslogs-group: BiopathLogGroup 
  #     awslogs-region: us-west-2
  #     awslogs-stream-prefix: