# docker-compose.yaml
#
# Docker compose file for launching and running both frontend and backend
# docker containers for the Biopath app
# 

version: "3.2"
services:
  db:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    volumes: # you must set the environment variable BIOPATH_ROOT_PATH on your machine
             #  for me this was just
             #   'export BIOPATH_ROOT_PATH="~/Users/joshuaschmitz/Projects/BioPath"'
      - "${BIOPATH_ROOT_PATH}/postgres:/var/lib/postgresql/data/"
    environment:
      # these are the same as those in backend container
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=BioPath
    ports:
      - '5432:5432'

  backend:
    container_name: backend
    platform: linux/amd64
    #   Not sure if we should actually makemigrations and migrate every startup, but it works for now
    #command: bash -c "/app/api/startup.sh"

    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ENV=${DJANGO_ENV}
      # TODO: change username, password, email
      # django admin login
      # - DJANGO_ADMIN_USER=root
      # - DJANGO_ADMIN_PASS=root
      # - DJANGO_ADMIN_EMAIL=root@root.com

      # # These are the same as those in db container
      # # TODO: change username, password
      # - POSTGRES_DB=BioPath
      # - POSTGRES_USER=username
      # - POSTGRES_PASSWORD=password
      # - POSTGRES_DB_HOST=db
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: backend
    ports:
      - "8000:8000"
    depends_on:
      - db

    # comment out dependancy for now
    # depends_on:
    #   - db
      # - redis
    # networks:
    #   - db-net

  # frontend:
  #   container_name: frontend
  #   restart: always
  #   command : npm start
  #   build:
  #     context: ./frontend/
  #     dockerfile: Dockerfile.local
  #   ports:
  #     - "3000:3000"
  #   stdin_open: true
  #   depends_on:
  #     - backend


# Josh S - This was unneeded for now; removed to decrease complexity
# networks:
#   db-net:
#     driver: bridge