
import getEndpointHeader from "./requestConfig";

// for this file, nothing attached like there is an attachment for the api/
let dataSourceAddressHeader = getEndpointHeader() 


/**
 * register a new user
 * @param {string} username 
 * @param {string} password 
 */
const register = async (username, password) => {
  let endpointExtension = "register/"
  let requestUrl = dataSourceAddressHeader + endpointExtension;

  const data = {
    username,
    password
  }

  fetch(requestUrl, {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify(data)
  })
    .then(res => res.json())
    .catch(err => console.log(err))
}

/**
 * This is a function which should be responsible for logging in a user 
 * If the user is successfully logged in then the auth token generated by django 
 * will be placed in localStorage under "token"
 * @param {string} username 
 * @param {string} password
 */
const login = async (username, password) => {
  let endpointExtension = "login/"
  let requestUrl = dataSourceAddressHeader + endpointExtension;

  const data = {
    username,
    password
  }

  fetch(requestUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(data)
    })
      .then(res => {
        if (!res.ok) {
          throw new Error("Login Failed");
        }
        return res.json()
      })
      .then(data => {
        localStorage.setItem("token", data.token)
      })
      .catch(err => console.error(err));
} 

export {
  register,
  login
}