

FROM python:3
WORKDIR /app/api
COPY . ./
RUN pip install -r requirements.txt
EXPOSE 8000

CMD ["python3", "manage.py makemigrations"]
CMD ["python3", "manage.py migrate"]

CMD ["gunicorn", "biopath.wsgi:application", "--bind", "0.0.0.0:8000"]