

FROM python:3
WORKDIR /app/api
COPY . ./
RUN pip install -r requirements.txt
EXPOSE 8000

ENTRYPOINT ["python3"]
CMD ["manage.py", "makemigrations"]
CMD ["manage.py", "migrate"]
CMD ["manage.py", "runserver", "0.0.0.0:8000"]