name: AWS Deployment

# when we merge a pull request into the main branch this file will be run
on:
  push:
    branches: [main]


jobs:
  BuildDockerImages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
        docker build -t biopath_frontend:frontend_latest ./frontend/
        docker build -t biopath_backend:backend_latest ./backend/
        

